//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSharp.SiteBase.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSharp.SiteBase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”不是有效的上下文初始化类型 的本地化字符串。
        /// </summary>
        internal static string DatabaseInitializer_TypeNotDatabaseInitializer {
            get {
                return ResourceManager.GetString("DatabaseInitializer_TypeNotDatabaseInitializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体类“{0}”所属的上下文“{1}”获取失败 的本地化字符串。
        /// </summary>
        internal static string DbContextTypeResolver_DbContextResolveFailed {
            get {
                return ResourceManager.GetString("DbContextTypeResolver_DbContextResolveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MVC初始化器不能为空，请为FrameworkInitializer.MvcIocInitializer属性赋值 的本地化字符串。
        /// </summary>
        internal static string FrameworkInitializer_MvcIoCInitializerNull {
            get {
                return ResourceManager.GetString("FrameworkInitializer_MvcIoCInitializerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”不是MVC控制器类型 的本地化字符串。
        /// </summary>
        internal static string MvcActionMethodInfoFinder_TypeNotMvcControllerType {
            get {
                return ResourceManager.GetString("MvcActionMethodInfoFinder_TypeNotMvcControllerType", resourceCulture);
            }
        }
    }
}
